version: 2.1

executors:
  docker-executor:
    machine:
      image: ubuntu-2204:current

orbs:
  ruby: circleci/ruby@2.1.4
  browser-tools: circleci/browser-tools@1.4.8
  docker: circleci/docker@2.8.2

jobs:
  test:
    docker:
      - image: cimg/ruby:3.3.4
        environment:
          RAILS_ENV: test
      - image: cimg/postgres:13.3-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_database
          POSTGRES_PASSWORD: mysecretpassword
      - image: redis:7.0
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Bundle Install
          command: bundle install --jobs=4 --retry=3
      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      - run:
          name: Run RSpec tests
          command: bundle exec rspec
      - store_artifacts:
          path: coverage



workflows:
  version: 2
  test:
    jobs:
      - test
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          dockerfile: ./docker/Dockerfile.dev
          remote-docker-version: 20.10.12
          update-description: true
          use-buildkit: true
          use-remote-docker: true
          use-docker-credentials-store: true
          tag: "rc"
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_TOKEN

